service: rootspyro-api

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    MONGODB_STR: ${env:MONGODB_STR}
    SECRET: ${env:SECRET}


functions:
  main:
    handler: dist/lambda.handler
    events:
      - http:
          method: ANY
          path: /
          cors:
            origins: 
            - 'https://portfolio-ui-ten.vercel.app'
            allowCredentials: true
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - charset        

      - http:
          method: ANY
          path: '{proxy+}'
          cors: 
            origins: 
            - 'https://portfolio-ui-ten.vercel.app'
            allowCredentials: true
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - charset        
        
